after_script:
- bash <(curl -s https://codecov.io/bash)
dotnet: 2.2.1
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: csharp
mono: none
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: gmBz4OsIDl2uMLh62bMFkQfxqJUqcE093UqXtAjEqefsSMPaVo7pBa7UQJ0JcNY3rbb7DqbuIVv6KlfkU7W6ulZ4e3lA3WytvnpAtrEN94IVdFoFAP5JSioUUsnu9iz9ui8A5k67RnjICQZb8JV/X2MgQ/D0WHeD2LWkvmjNn9RlgWVC8al8tj1teGjZf4ZOrCrJUQ07Ulkn6qegU3w0DcaBCIhF992aDYQfITQBhJcgRWZWMaHUMubkQqQQTfQb9JTN9s5c5vMgDYaNIPOfqVzeBJoJz1+slF6PItH1G1QFxNkfF3vR6fHhhvIcP1Fwoxa58NMcOd+3w+SOyJ1XuqgOZ6CTve1yjaal2mOeIv309UxJ14PLEBB4P1k6paJhkvwxZP/SvIIUNfkeBWO4ePX30ogY7pV3CNMpTQGB0aIBWZVfujN33EO5pgM2Ti0NfyK3gUm8Tqnokl+psO+ZAl0YFhW7vP7kDXN/eHHJtUeiUp2eN4r8HlOnnfoOHY5U3eyyyBrGJ1kQHTZCZLckTiZKC+HURZ4FoKXoOWrA2TfhTisB0gkOqALLxkDdWeoylHNtyO4gJFT+MAfjVE7urC9qcPLUNYtHJtH0dj1R1dZe6POqY2/1YYxS4qLdcpm7s5/Wk8jrDao7+AqQRXsdkzc8dn3GRfOdPnL0AZwZkgE=
script:
- dotnet restore
- dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Threshold=90
solution: All.sln
